/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _COMPLEX_CALCULATOR_H_RPCGEN
#define _COMPLEX_CALCULATOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


typedef struct {
	u_int vector_operando_len;
	int *vector_operando_val;
} vector_operando;

struct complex_calculator_res {
	int errnum;
	union {
		struct {
			u_int res_len;
			int *res_val;
		} res;
	} complex_calculator_res_u;
};
typedef struct complex_calculator_res complex_calculator_res;

struct calculate_1_argument {
	vector_operando arg1;
	char arg2;
	vector_operando arg3;
};
typedef struct calculate_1_argument calculate_1_argument;

#define COMPLEX_CALCULATOR 0x20000002
#define CCALVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALCULATE 1
extern  complex_calculator_res * calculate_1(vector_operando , char , vector_operando , CLIENT *);
extern  complex_calculator_res * calculate_1_svc(vector_operando , char , vector_operando , struct svc_req *);
extern int complex_calculator_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALCULATE 1
extern  complex_calculator_res * calculate_1();
extern  complex_calculator_res * calculate_1_svc();
extern int complex_calculator_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_vector_operando (XDR *, vector_operando*);
extern  bool_t xdr_complex_calculator_res (XDR *, complex_calculator_res*);
extern  bool_t xdr_calculate_1_argument (XDR *, calculate_1_argument*);

#else /* K&R C */
extern bool_t xdr_vector_operando ();
extern bool_t xdr_complex_calculator_res ();
extern bool_t xdr_calculate_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_COMPLEX_CALCULATOR_H_RPCGEN */
