/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "complex_calculator.h"
#include <stdio.h>

complex_calculator_res2 *calculate_complex_1_svc(vector_operando2 op1,
                                                 char operator,
                                                 vector_operando2 op3,
                                                 struct svc_req *rqstp) {
  static complex_calculator_res2 result;
  result.complex_calculator_res2_u.res.res_val =
      (int *)malloc(op1.vector_operando2_len * sizeof(int));
  result.complex_calculator_res2_u.res.res_len = op1.vector_operando2_len;

  /*
   * insert server code here
   */
  if (op1.vector_operando2_len != op3.vector_operando2_len) {
    result.errnum = 1;
    return &result;
  }

  switch (operator) {
  case '+':
    result.errnum = 0;
    result.complex_calculator_res2_u.res.res_len = op1.vector_operando2_len;
    for (int i = 0; i < op1.vector_operando2_len; i++) {
      result.complex_calculator_res2_u.res.res_val[i] =
          op1.vector_operando2_val[i] + op3.vector_operando2_val[i];
    }
    break;

  case '-':
    result.errnum = 0;
    result.complex_calculator_res2_u.res.res_len = op1.vector_operando2_len;
    for (int i = 0; i < op1.vector_operando2_len; i++) {
      result.complex_calculator_res2_u.res.res_val[i] =
          op1.vector_operando2_val[i] - op3.vector_operando2_val[i];
    }
    break;

  default:
    result.errnum = 2;
    break;
  }

  return &result;
}
