/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculator.h"
#include "rpc/types.h"
#include <stdio.h>
#include <stdlib.h>

int getArrayLength(char *input) {
  int count = 0;
  for (int i = 0; input[i] != '\0'; i++) {
    if (input[i] == ',' || input[i] == ']') {
      count++;
    }
  }
  return count;
}

vector_operando parseArray(char *input) {
  int count = 0;
  int *array = NULL;
  vector_operando op;

  count = getArrayLength(input);
  op.vector_operando_len = count;
  printf("Vector con tamaño: %d\n", op.vector_operando_len);

  // Allocate memory for the array
  array = (int *)malloc(count * sizeof(int));

  // Parse the array elements
  int index = 0;
  int num = 0;
  sscanf(input, "[%d", &num);
  array[index++] = num;
  for (int i = 1; input[i] != '\0'; i++) {
    if (input[i] == ',' || input[i] == ']') {
      if (input[i] == ',') {
        sscanf(input + i + 1, "%d", &num);
        array[index++] = num;
      }
      i++;
    }
  }

  op.vector_operando_val = array;
  return op;
}

void calculator_1(char *host, float num1, char operator, float num2) {
  CLIENT *clnt;
  calculator_res *result_1;

#ifndef DEBUG
  clnt = clnt_create(host, CALCULATOR, CALVER, "udp");
  if (clnt == NULL) {
    clnt_pcreateerror(host);
    exit(1);
  }
#endif /* DEBUG */

  result_1 = calculate_1(num1, operator, num2, clnt);
  if (result_1 == (calculator_res *)NULL) {
    clnt_perror(clnt, "call failed");
  }

  if (result_1->errnum != 0) {
    printf("Error, not a valid operation: %d\n", result_1->errnum);
    exit(1);
  }

  printf("Resultado: %f\n", result_1->calculator_res_u.result);

#ifndef DEBUG
  clnt_destroy(clnt);
#endif /* DEBUG */
}

void complex_calculator_1(char *host, vector_operando vec1, char operator,
                          vector_operando vec2) {
  CLIENT *clnt;
  complex_calculator_res *result_1;

#ifndef DEBUG
  clnt = clnt_create(host, CALCULATOR, CALVER, "udp");
  if (clnt == NULL) {
    clnt_pcreateerror(host);
    exit(1);
  }
#endif /* DEBUG */

  result_1 = complex_calculate_1(vec1, operator, vec2, clnt);
  if (result_1 == (calculator_res *)NULL) {
    clnt_perror(clnt, "call failed");
  }

  if (result_1->errnum != 0) {
    printf("Error, not a valid operation: %d\n", result_1->errnum);
    exit(1);
  }

#ifndef DEBUG
  clnt_destroy(clnt);
#endif /* DEBUG */
}

void complex_calculator_2(char *host, vector_operando vec1, char operator,
                          float number) {
  CLIENT *clnt;
  complex_calculator_res *result_1;

#ifndef DEBUG
  clnt = clnt_create(host, CALCULATOR, CALVER, "udp");
  if (clnt == NULL) {
    clnt_pcreateerror(host);
    exit(1);
  }
#endif /* DEBUG */

  result_1 = complex_calculate_2(vec1, operator, number, clnt);
  if (result_1 == (calculator_res *)NULL) {
    clnt_perror(clnt, "call failed");
  }

  if (result_1->errnum != 0) {
    printf("Error, not a valid operation: %d\n", result_1->errnum);
    exit(1);
  }

#ifndef DEBUG
  clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[]) {
  char *host;
  char num1[100];
  char operator;
  char num2[100];
  bool_t first_is_vector = FALSE;
  bool_t second_is_vector = FALSE;

  if (argc != 2) {
    printf("Uso del programa: %s host\n", argv[0]);
    exit(1);
  }
  host = argv[1];

  printf("Ingrese el primer número o vector: \n");
  scanf("%[^\n]s", num1);
  printf("El primer número o vector es: %s\n", num1);
  printf("Ingrese el operador (+, -, x, /): \n");
  scanf(" %c", &operator);
  printf("El operador es: %c\n", operator);
  printf("Ingrese el segundo número o vector: \n");
  scanf(" %[^\n]s", num2);
  vector_operando vec_operando1;
  vector_operando vec_operando2;
  float operando1;
  float operando2;

  switch (num1[0]) {
  case '[':
    vec_operando1 = parseArray(num1);
    first_is_vector = TRUE;
    break;
  default:
    operando1 = atof(num1);
    break;
  }

  switch (num2[0]) {
  case '[':
    vec_operando2 = parseArray(num2);
    second_is_vector = TRUE;
    break;
  default:
    operando2 = atof(num2);
    break;
  }

  if (!first_is_vector && !second_is_vector) {
    printf("Operandos no vectores, llamando para función simple\n");
    calculator_1(host, operando1, operator, operando2);
    exit(0);
  } else if (first_is_vector && second_is_vector) {
    printf("Operandos vectores, llamando para función compleja\n");
    complex_calculator_1(host, vec_operando1, operator, vec_operando2);
    exit(0);
  } else if (first_is_vector) {
    printf("Primer operando vector, llamando para función compleja\n");
    complex_calculator_2(host, vec_operando1, operator, operando2);
    exit(0);
  } else if (second_is_vector) {
    printf("Segundo operando vector, llamando para función compleja\n");
    complex_calculator_2(host, vec_operando2, operator, operando1);
    exit(0);
  }

  //
}
