/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULATOR_H_RPCGEN
#define _CALCULATOR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct calculator_res {
	int errnum;
	union {
		float result;
	} calculator_res_u;
};
typedef struct calculator_res calculator_res;

struct calculate_1_argument {
	float arg1;
	char arg2;
	float arg3;
};
typedef struct calculate_1_argument calculate_1_argument;

#define CALCULATOR 0x20000001
#define CALVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define CALCULATE 1
extern  calculator_res * calculate_1(float , char , float , CLIENT *);
extern  calculator_res * calculate_1_svc(float , char , float , struct svc_req *);
extern int calculator_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define CALCULATE 1
extern  calculator_res * calculate_1();
extern  calculator_res * calculate_1_svc();
extern int calculator_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_calculator_res (XDR *, calculator_res*);
extern  bool_t xdr_calculate_1_argument (XDR *, calculate_1_argument*);

#else /* K&R C */
extern bool_t xdr_calculator_res ();
extern bool_t xdr_calculate_1_argument ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULATOR_H_RPCGEN */
