/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculator.h"
#include <stdio.h>
#include <stdlib.h>

int getArrayLength(char *input) {
  int count = 0;
  for (int i = 0; input[i] != '\0'; i++) {
    if (input[i] == ',' || input[i] == ']') {
      count++;
    }
  }
  return count;
}

vector_operando parseArray(char *input) {
  int count = 0;
  int *array = NULL;
  vector_operando op;

  count = getArrayLength(input);
  op.vector_operando_len = count;
  printf("Vector con tamaño: %d\n", op.vector_operando_len);

  // Allocate memory for the array
  array = (int *)malloc(count * sizeof(int));

  // Parse the array elements
  int index = 0;
  int num = 0;
  sscanf(input, "[%d", &num);
  array[index++] = num;
  for (int i = 1; input[i] != '\0'; i++) {
    if (input[i] == ',' || input[i] == ']') {
      if (input[i] == ',') {
        sscanf(input + i + 1, "%d", &num);
        array[index++] = num;
      }
      i++;
    }
  }

  op.vector_operando_val = array;
  return op;
}

void calculator_1(char *host, float num1, char operator, float num2) {
  CLIENT *clnt;
  calculator_res *result_1;

#ifndef DEBUG
  clnt = clnt_create(host, CALCULATOR, CALVER, "udp");
  if (clnt == NULL) {
    clnt_pcreateerror(host);
    exit(1);
  }
#endif /* DEBUG */

  result_1 = calculate_1(num1, operator, num2, clnt);
  if (result_1 == (calculator_res *)NULL) {
    clnt_perror(clnt, "call failed");
  }

  if (result_1->errnum != 0) {
    printf("Error, not a valid operation: %d\n", result_1->errnum);
    exit(1);
  }

  printf("Resultado: %f\n", result_1->calculator_res_u.result);

#ifndef DEBUG
  clnt_destroy(clnt);
#endif /* DEBUG */
}

void complex_calculator_1(char *host, vector_operando vec1, char operator,
                          vector_operando vec2) {
  CLIENT *clnt;
  complex_calculator_res *result_1;

#ifndef DEBUG
  clnt = clnt_create(host, CALCULATOR, CALVER, "udp");
  if (clnt == NULL) {
    clnt_pcreateerror(host);
    exit(1);
  }
#endif /* DEBUG */

  result_1 = complex_calculate_1(vec1, operator, vec2, clnt);
  if (result_1 == (calculator_res *)NULL) {
    clnt_perror(clnt, "call failed");
  }

  if (result_1->errnum != 0) {
    printf("Error, not a valid operation: %d\n", result_1->errnum);
    exit(1);
  }

#ifndef DEBUG
  clnt_destroy(clnt);
#endif /* DEBUG */
}

int main(int argc, char *argv[]) {
  char *host;
  float num1;
  char operator;
  float num2;

  if (argc != 2) {
    printf("Uso del programa: %s host\n", argv[0]);
    exit(1);
  }
  host = argv[1];

  printf("Ingrese el primer número o vector: ");
  scanf("%f", &num1);
  printf("Ingrese el operador (+, -, x, /): ");
  scanf(" %c", &operator);
  printf("Ingrese el segundo número o vector: ");
  scanf("%f", &num2);

  vector_operando vector_operando;
  vector_operando.vector_operando_val = (float *)malloc(2 * sizeof(float));
  vector_operando.vector_operando_len = 2;
  vector_operando.vector_operando_val[0] = num1;
  vector_operando.vector_operando_val[1] = num2;

  calculator_1(host, num1, operator, num2);
  complex_calculator_1(host, vector_operando, operator, vector_operando);
  exit(0);
}
