/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "calculator.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

calculator_res *
calculate_1(float arg1, char arg2, float arg3,  CLIENT *clnt)
{
	calculate_1_argument arg;
	static calculator_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	if (clnt_call (clnt, CALCULATE, (xdrproc_t) xdr_calculate_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_calculator_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}

complex_calculator_res *
complex_calculate_1(vector_operando arg1, char arg2, vector_operando arg3,  CLIENT *clnt)
{
	complex_calculate_1_argument arg;
	static complex_calculator_res clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	arg.arg1 = arg1;
	arg.arg2 = arg2;
	arg.arg3 = arg3;
	if (clnt_call (clnt, COMPLEX_CALCULATE, (xdrproc_t) xdr_complex_calculate_1_argument, (caddr_t) &arg,
		(xdrproc_t) xdr_complex_calculator_res, (caddr_t) &clnt_res,
		TIMEOUT) != RPC_SUCCESS) {
		return (NULL);
	}
	return (&clnt_res);
}
