/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "./calculator.h"
#include "./complex/complex_calculator.h"
#include <stdio.h>

complex_calculator_res complex_calculator_1(char *host, vector_operando2 op1,
                                            char operator,
                                            vector_operando2 op2) {
  CLIENT *clnt;
  complex_calculator_res2 *result_1;

#ifndef DEBUG
  clnt = clnt_create(host, COMPLEX_CALCULATOR, CCALVER, "udp");
  if (clnt == NULL) {
    clnt_pcreateerror(host);
    exit(1);
  }
#endif /* DEBUG */

  result_1 = calculate_complex_1(op1, operator, op2, clnt);
  if (result_1 == (complex_calculator_res2 *)NULL) {
    clnt_perror(clnt, "call failed");
  } else if (result_1->errnum != 0) {
    printf("Error: %d\n", result_1->errnum);
  }

  printf("Resultado: ");
  for (int i = 0; i < result_1->complex_calculator_res2_u.res.res_len; i++) {
    printf("%f ", result_1->complex_calculator_res2_u.res.res_val[i]);
  }
  printf("\n");
  static complex_calculator_res result;
  result.errnum = result_1->errnum;
  result.complex_calculator_res_u.res.res_len =
      result_1->complex_calculator_res2_u.res.res_len;
  result.complex_calculator_res_u.res.res_val =
      result_1->complex_calculator_res2_u.res.res_val;
#ifndef DEBUG
  clnt_destroy(clnt);
#endif /* DEBUG */
  return result;
}

calculator_res *calculate_1_svc(float num1, char operator, float num2,
                                struct svc_req *rqstp) {
  static calculator_res result;

  /*
   * insert server code here
   */
  printf("Llamada para operación %f %c %f\n", num1, operator, num2);
  result.errnum = 0;
  switch (operator) {
  case '+':
    result.calculator_res_u.result = num1 + num2;
    break;
  case '-':
    result.calculator_res_u.result = num1 - num2;
    break;
  case 'x':
    result.calculator_res_u.result = num1 * num2;
    break;
  case '/':
    if (num2 == 0) {
      result.errnum = 1;
      return &result;
    }
    result.calculator_res_u.result = num1 / num2;
    break;
  default:
    result.errnum = 1;
    return &result;
  }

  return &result;
}

complex_calculator_res *complex_calculate_1_svc(vector_operando arg1,
                                                char operator,
                                                vector_operando arg2,
                                                struct svc_req *rqstp) {
  printf("Función demasiado compleja para este servidor, llamando a servidor "
         "más capacitado.\n");
  vector_operando2 op1;
  vector_operando2 op2;
  op1.vector_operando2_len = arg1.vector_operando_len;
  op1.vector_operando2_val = arg1.vector_operando_val;
  op2.vector_operando2_len = arg2.vector_operando_len;
  op2.vector_operando2_val = arg2.vector_operando_val;
  static complex_calculator_res result;
  result = complex_calculator_1("localhost", op1, operator, op2);
  printf("Resultado: ");
  for (int i = 0; i < result.complex_calculator_res_u.res.res_len; i++) {
    printf("%f ", result.complex_calculator_res_u.res.res_val[i]);
  }
  return &result;
}

complex_calculator_res *complex_calculate_2_svc(vector_operando arg1,
                                                char operator, float arg2,
                                                struct svc_req *rqstp) {
  printf("Función demasiado compleja para este servidor, llamando a servidor "
         "más capacitado.\n");
  static complex_calculator_res result;
  result.errnum = 0;
  return &result;
}
