services:
  servidor:
    container_name: servidor-p4
    build: 
      context: .
      dockerfile: ./Server.dockerfile
    volumes:
      - ./servidor/app:/app/src
    entrypoint: nodemon server.js
    ports:
      - 3000:3000
  agente:
    depends_on:
      - servidor
    container_name: agente-p4
    build: 
      context: .
      dockerfile: ./agente.dockerfile
    volumes:
      - ./agente/app:/app/src
    entrypoint: nodemon agente.js
    ports:
      - 3001:3001
